baseURL: http://glam-datasci.netlify.app/
languageCode: en-gb
title: GLAM Data Science Network

theme: PaperMod
params:
  description: "Data science for everyone!"
  defaultTheme: light

  socialIcons:
    - name: github
      url: "https://github.com/jezcope/glam-datasci"
    - name: rss
      url: "index.xml"

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    - name: Categories
      url: categories/
      weight: 10

privacy:
    vimeo:
        disabled: true
        simple: true

    twitter:
        disabled: true
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: true
        privacyEnhanced: true
