baseURL: https://glam-datasci.netlify.app/
languageCode: en-gb
title: GLAM Data Science Network
copyright: >
  [![Creative Commons License](https://i.creativecommons.org/l/by-sa/4.0/80x15.png)](http://creativecommons.org/licenses/by-sa/4.0/) Except where noted, all content is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).

theme: PaperMod
params:
  description: "Data science for everyone!"
  defaultTheme: light

  socialIcons:
    - name: github
      url: "https://github.com/jezcope/glam-datasci"
    - name: rss
      url: "index.xml"

menu:
  main:
    - name: GitHub
      url: "https://github.com/jezcope/glam-datasci"
      weight: 100

permalinks:
  posts: /:year/:month/:slug/

outputs:
  home:
    - HTML
    - RSS
    - JSON

privacy:
    vimeo:
        disabled: true
        simple: true

    twitter:
        disabled: true
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: true
        privacyEnhanced: true
