baseURL: http://glam-datasci.netlify.app/
languageCode: en-gb
title: GLAM Data Science Network

theme: PaperMod
params:
  description: "Data science for everyone!"
  defaultTheme: light

  socialIcons:
    - name: github
      url: "https://github.com/jezcope/glam-datasci"
    - name: rss
      url: "index.xml"

menu:
  main:
    - name: Blog
      url: blog
      weight: 5
    - name: Get involved
      url: get-involved
      weight: 10
    - name: Project
      url: project
      weight: 20
    - name: Search
      url: search/
      weight: 80

outputs:
  home:
    - HTML
    - RSS
    - JSON

privacy:
    vimeo:
        disabled: true
        simple: true

    twitter:
        disabled: true
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: true
        privacyEnhanced: true
