baseURL: https://glamdatasci.network/
languageCode: en-gb
title: GLAM Data Science Network
copyright: >
   Except where noted, all content is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/) ·
   Project supported by a [Software Sustainability Institute Fellowship](https://software.ac.uk/programmes-and-events/fellowship-programme) ·
   Web hosting provided free by [Netlify](https://netlify.com)

theme: PaperMod
params:
  description: "Data science for everyone!"
  defaultTheme: light

  socialIcons:
    - name: github
      url: "https://github.com/glamdatasci/website"
    - name: rss
      url: "index.xml"

enableEmoji: true

menu:
  main:
    - name: GitHub
      url: "https://github.com/glamdatasci/website"
      weight: 100

permalinks:
  posts: /:year/:month/:slug/

outputs:
  home:
    - HTML
    - RSS
    - JSON

privacy:
    vimeo:
        disabled: true
        simple: true

    twitter:
        disabled: true
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: true
        privacyEnhanced: true
